name: playground
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  observe: '^0.13.1'
  angular2: '^<%= packageJson.version %>'
  angular2_material: '^<%= packageJson.version %>'
  browser: '^0.10.0'
dev_dependencies:
  guinness: '^0.1.17'
  benchpress:
    path: ../benchpress
dependency_overrides:
  angular2:
    path: ../angular2
  angular2_material:
    path: ../angular2_material
transformers:
- angular2:
    platform_directives: 'package:angular2/src/common/directives.dart#CORE_DIRECTIVES'
    entry_points:
        - web/src/gestures/index.dart
        - web/src/hello_world/index.dart
        - web/src/key_events/index.dart
        - web/src/sourcemap/index.dart
        - web/src/todo/index.dart
        - web/src/order_management/index.dart
        - web/src/model_driven_forms/index.dart
        - web/src/observable_models/index.dart
        - web/src/person_management/index.dart
        - web/src/routing/index.dart
        - web/src/template_driven_forms/index.dart
        - web/src/zippy_component/index.dart
        - web/src/relative_assets/index.dart
        - web/src/svg/index.dart
        - web/src/material/button/index.dart
        - web/src/material/checkbox/index.dart
        - web/src/material/dialog/index.dart
        - web/src/material/grid_list/index.dart
        - web/src/material/input/index.dart
        - web/src/material/progress-linear/index.dart
        - web/src/material/radio/index.dart
        - web/src/material/switcher/index.dart

        # These entrypoints are disabled untl the transformer supports UI bootstrap (issue #3971)
        # - web/src/web_workers/message_broker/index.dart
        # - web/src/web_workers/kitchen_sink/index.dart
        # - web/src/web_workers/todo/index.dart
        # - web/src/web_workers/todo/server_index.dart
        # - web/src/web_workers/todo/background_index.dart
        # - web/src/web_workers/message_broker/background_index.dart
        # - web/src/web_workers/kitchen_sink/background_index.dart
        #
        # This entrypoint is not needed:
        # - web/src/material/demo_common.dart

- $dart2js:
    minify: false
    commandLineOptions:
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors
    # Uncomment to generate summaries from dart2js
    # - --dump-info
